import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextFont } from "@next/font";

const geistSans: NextFont = localFont({
  src: "./fonts/PPMondwest-Regular.otf",
  variable: "--font-geist-sans",
  weight: "900",
});

const geistSansBold: NextFont = localFont({
  src: "./fonts/PPNeueBit-Bold.otf",
  variable: "--font-geist-sans",
  weight: "900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(geistSans)
  return (
    <html lang="en">
      <body
        className={`font-sans
         w-full h-full antialiased bg-background-bg text-white container mx-auto  relative
        overflow-auto text-sm
        `}
        style={{ fontFamily: (geistSans.style.fontFamily, geistSansBold.style.fontFamily) }}
      >
        {children}
      </body>
    </html>
  );
}
